# Generated by Django 5.1.4 on 2025-04-26 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Сумма (в копейках)')),
                ('currency', models.CharField(choices=[('RUB', 'RUB')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'баланс',
                'verbose_name_plural': 'балансы',
                'db_table': 'balance',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Сумма (в копейках)')),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('debit', 'Списание')], max_length=7, verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'транзакции',
                'verbose_name_plural': 'транзакции',
                'db_table': 'transactions',
            },
        ),
    ]
