# Generated by Django 5.1.4 on 2025-04-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_service_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='is_provided',
            field=models.BooleanField(default=False, verbose_name='Предоставлена ли услуга?'),
        ),
    ]
