networks:
  ml-service:
    driver: bridge

services:
  db:
    image: postgres:14.1
    hostname: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5436:5432"
    networks:
      - ml-service

  redis:
    image: redis:latest
    hostname: redis
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - ./redis/data:/data
    environment:
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - ml-service

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - ml-service

  api:
    build:
      context: packages/api
      dockerfile: Dockerfile
    hostname: api
    restart: always
    volumes:
      - ./packages/api/src/:/app/src
      - ./packages/api/static/:/var/www/html/static/
      - shared_temp:/tmp
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - ml-service

  api_celery:
    build:
      context: packages/api
      dockerfile: Dockerfile
    container_name: api_celery
    command: "celery -A api.celery_config:app worker -l INFO -E"
    restart: always
    volumes:
      - ./packages/api/src/:/app/src
      - shared_temp:/tmp
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - ml-service

  web:
    build:
      context: packages/web
      dockerfile: Dockerfile
    hostname: web
    restart: always
    volumes:
      - ./packages/web/src/:/app/src
      - ./packages/web/static/:/var/www/html/static/
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ml-service

volumes:
  shared_temp: