[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [
  "venv",
  "migrations",
  "manage.py",
  "parser"
]

[tool.mypy]
mypy_path = "./packages/api/src"
python_version = "3.11"
ignore_missing_imports_per_module = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
strict = true
implicit_reexport = true
plugins = [
  "mypy_django_plugin.main",
]
exclude = [
  ".venv",
  "migrations",
  "parser"
]

[tool.django-stubs]
django_settings_module = "api.settings"
